#!/usr/bin/env bash
set -euo pipefail

#######################################
# Per-project install script
# Generated by: notellm init
# 
# This script is kept for reference and can be re-run
# to reinstall dependencies without full init.
#######################################

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}▶${NC} Installing/updating dependencies..."

if ! command -v uv &> /dev/null; then
    echo "Installing uv..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    [ -f "$HOME/.local/bin/env" ] && source "$HOME/.local/bin/env"
fi

uv sync

echo -e "${GREEN}✓${NC} Dependencies installed"
echo ""
echo "Start server:  notellm start"
echo "Create notebook: notellm new <n>"
